### PR TITLE
Fix the Mod & Project names and Namespaces being different

### PR DESCRIPTION
**Pull request by misterslime**
**Description:**
Renames everything with Cascade in its name and changes all the namespaces to TwilightEgress.

**Reason:**
Mod won't build lmao 💀.

### CODE REVIEW

**Comment by JasperDawg** [comment]
LGTM!

**Comment by SpencerDawg** [comment]
Testing!

**Comment by SpencerDawg** [comment]
hi cog

**Comment by SpencerDawg** [comment]
hi again cog

**Pull request merged**
